"""Brand logo installer / integrity generator for Sudarshana Chakra.

Single entry point used to (re)install the immutable brand logo and its derived
asset variants. It:

  1. Loads a source image (the cinematic Sudarshana Chakra logo).
  2. Writes the canonical, *read-only* assets:
        assets/sudarshana_chakra_logo_core.png   (primary banner, ~16:9)
        assets/app_icon_core.png                 (square desktop/tray icon)
        assets/favicon.ico                       (multi-size browser favicon)
  3. Regenerates ``core/brand_logo_asset.py`` with embedded Base64 copies and
     SHA-256 fingerprints so the running application can self-heal the assets.

Usage
-----
    # install the official logo (recommended)
    python tools/set_brand_logo.py --source path/to/image_26.png

    # derive the square icon from a different (chakra) crop
    python tools/set_brand_logo.py --source logo.png --icon-source chakra.png

    # keep the source's native aspect ratio instead of padding to 16:9
    python tools/set_brand_logo.py --source logo.png --no-frame
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import stat
from pathlib import Path

from PIL import Image

BASE_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = BASE_DIR / "assets"
LOGO_PATH = ASSETS_DIR / "sudarshana_chakra_logo_core.png"
ICON_PATH = ASSETS_DIR / "app_icon_core.png"
FAVICON_PATH = ASSETS_DIR / "favicon.ico"
EMBED_PATH = BASE_DIR / "core" / "brand_logo_asset.py"

DEFAULT_SOURCE = ASSETS_DIR / "sudarshana_chakra_logo_core.png"
DEFAULT_ICON_SOURCE = None

ICON_SIZE = 512
FAVICON_SIZES = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
BANNER_ASPECT = 16 / 9


def _load_rgba(path: Path) -> Image.Image:
    img = Image.open(path)
    return img.convert("RGBA")


def _frame_16x9(img: Image.Image) -> Image.Image:
    """Center the image on a transparent 16:9 canvas (contain, no crop)."""
    w, h = img.size
    if w / h > BANNER_ASPECT:
        cw, ch = w, max(1, round(w / BANNER_ASPECT))
    else:
        ch, cw = h, max(1, round(h * BANNER_ASPECT))
    canvas = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    canvas.paste(img, ((cw - w) // 2, (ch - h) // 2), img)
    return canvas


def _square(img: Image.Image, size: int) -> Image.Image:
    """Center-crop to a square then resize (keeps the chakra centered)."""
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    cropped = img.crop((left, top, left + side, top + side))
    return cropped.resize((size, size), Image.LANCZOS)


def _make_writeable(path: Path) -> None:
    try:
        if path.exists():
            path.chmod(stat.S_IWRITE | stat.S_IREAD)
    except Exception:
        pass


def _make_readonly(path: Path) -> None:
    try:
        path.chmod(stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)
    except Exception:
        pass


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def install(source: Path, icon_source: Path | None, frame: bool) -> None:
    if not source.is_file():
        raise SystemExit(f"Source logo not found: {source}")

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    logo = _load_rgba(source)
    if frame:
        logo = _frame_16x9(logo)

    icon_base = _load_rgba(icon_source) if (icon_source and icon_source.is_file()) else _load_rgba(source)
    icon = _square(icon_base, ICON_SIZE)

    _make_writeable(LOGO_PATH)
    _make_writeable(ICON_PATH)
    _make_writeable(FAVICON_PATH)

    logo.save(LOGO_PATH, "PNG")
    icon.save(ICON_PATH, "PNG")
    icon.save(FAVICON_PATH, "ICO", sizes=FAVICON_SIZES)

    _make_readonly(LOGO_PATH)
    _make_readonly(ICON_PATH)
    _make_readonly(FAVICON_PATH)

    logo_bytes = LOGO_PATH.read_bytes()
    icon_bytes = ICON_PATH.read_bytes()
    favicon_bytes = FAVICON_PATH.read_bytes()

    def b64(data: bytes) -> str:
        return base64.b64encode(data).decode("ascii")

    module = f'''"""AUTO-GENERATED by tools/set_brand_logo.py -- do not edit by hand.

Embedded Base64 copies + SHA-256 fingerprints of the immutable Sudarshana
Chakra brand assets. Regenerate with::

    python tools/set_brand_logo.py --source <logo.png>
"""

LOGO_BYTES_B64 = "{b64(logo_bytes)}"
LOGO_SHA256 = "{_sha256(logo_bytes)}"
LOGO_WIDTH = {logo.size[0]}
LOGO_HEIGHT = {logo.size[1]}

ICON_BYTES_B64 = "{b64(icon_bytes)}"
ICON_SHA256 = "{_sha256(icon_bytes)}"
ICON_WIDTH = {icon.size[0]}
ICON_HEIGHT = {icon.size[1]}

FAVICON_BYTES_B64 = "{b64(favicon_bytes)}"
FAVICON_SHA256 = "{_sha256(favicon_bytes)}"
'''

    _make_writeable(EMBED_PATH)
    EMBED_PATH.write_text(module, encoding="utf-8")

    print(f"[ok] logo    {LOGO_PATH.name}   {logo.size[0]}x{logo.size[1]}  {len(logo_bytes):,} bytes  sha256={_sha256(logo_bytes)[:16]}")
    print(f"[ok] icon    {ICON_PATH.name}   {icon.size[0]}x{icon.size[1]}  {len(icon_bytes):,} bytes  sha256={_sha256(icon_bytes)[:16]}")
    print(f"[ok] favicon {FAVICON_PATH.name}  {len(favicon_bytes):,} bytes  sha256={_sha256(favicon_bytes)[:16]}")
    print(f"[ok] embedded constants -> {EMBED_PATH.relative_to(BASE_DIR)}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Install the immutable Sudarshana Chakra brand logo.")
    ap.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                    help="primary logo image (default: the installed assets/sudarshana_chakra_logo_core.png)")
    ap.add_argument("--icon-source", type=Path, default=None,
                    help="optional square chakra icon source (default: derive from --source)")
    ap.add_argument("--no-frame", action="store_true",
                    help="keep the source aspect ratio instead of padding to 16:9")
    args = ap.parse_args()

    install(args.source, args.icon_source, frame=not args.no_frame)


if __name__ == "__main__":
    main()